"""add_role_to_users

Revision ID: 871042bcebd7
Revises: 5eff44bbc8bb
Create Date: 2025-11-16 04:50:04.458427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871042bcebd7'
down_revision: Union[str, None] = '5eff44bbc8bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type
    userrole_enum = sa.Enum('ADMIN', 'TEACHER', 'STUDENT', 'PARENT', name='userrole')
    userrole_enum.create(op.get_bind(), checkfirst=True)

    # Add column as nullable first
    op.add_column('users', sa.Column('role', userrole_enum, nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE users SET role = 'STUDENT' WHERE role IS NULL")

    # Make the column non-nullable
    op.alter_column('users', 'role', nullable=False)

    # Create index
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
