"""init database

Revision ID: 5eff44bbc8bb
Revises: 
Create Date: 2025-11-14 16:52:06.699910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5eff44bbc8bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='exercisedifficulty'), nullable=False),
    sa.Column('exercise_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercises_difficulty_level'), 'exercises', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER', 'ESSAY', 'FILL_IN_BLANK', name='questiontype'), nullable=False),
    sa.Column('difficulty_level', sa.Enum('EASY', 'MEDIUM', 'HARD', name='questiondifficulty'), nullable=False),
    sa.Column('question_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_difficulty_level'), 'questions', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.create_index(op.f('ix_questions_type'), 'questions', ['type'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('VIDEO', 'ARTICLE', 'DOCUMENT', 'INTERACTIVE', 'EXTERNAL_LINK', 'SLIDE', name='resourcetype'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_metadata', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_id'), 'resources', ['id'], unique=False)
    op.create_index(op.f('ix_resources_type'), 'resources', ['type'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('grade_level', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('academic_year', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficultylevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_difficulty_level'), 'courses', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_user_id'), 'courses', ['user_id'], unique=False)
    op.create_table('profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), nullable=True),
    sa.Column('meta_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    op.create_index(op.f('ix_profiles_user_id'), 'profiles', ['user_id'], unique=True)
    op.create_table('enrollments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('enrollment_status', sa.Enum('ACTIVE', 'COMPLETED', 'DROPPED', 'PAUSED', name='enrollmentstatus'), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('certificate_issued', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_user_course_enrollment')
    )
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_enrollment_status'), 'enrollments', ['enrollment_status'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_enrollments_user_id'), 'enrollments', ['user_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('module_number', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficultylevel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_course_id'), 'modules', ['course_id'], unique=False)
    op.create_index(op.f('ix_modules_difficulty_level'), 'modules', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_modules_id'), 'modules', ['id'], unique=False)
    op.create_table('sections',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('section_number', sa.Integer(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=True),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficultylevel'), nullable=False),
    sa.Column('objectives', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sections_difficulty_level'), 'sections', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_sections_id'), 'sections', ['id'], unique=False)
    op.create_index(op.f('ix_sections_module_id'), 'sections', ['module_id'], unique=False)
    op.create_table('knowledge_points',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('kp_type', sa.Enum('CONCEPT', 'RULE', 'FORMULA', 'PROBLEM_TYPE', name='knowledgepointtype'), nullable=False),
    sa.Column('learning_objectives', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('difficulty_level', sa.Enum('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='difficultylevel'), nullable=False),
    sa.Column('estimated_time', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_points_code'), 'knowledge_points', ['code'], unique=True)
    op.create_index(op.f('ix_knowledge_points_course_id'), 'knowledge_points', ['course_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_difficulty_level'), 'knowledge_points', ['difficulty_level'], unique=False)
    op.create_index(op.f('ix_knowledge_points_id'), 'knowledge_points', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_kp_type'), 'knowledge_points', ['kp_type'], unique=False)
    op.create_index(op.f('ix_knowledge_points_module_id'), 'knowledge_points', ['module_id'], unique=False)
    op.create_index(op.f('ix_knowledge_points_section_id'), 'knowledge_points', ['section_id'], unique=False)
    op.create_table('assessment_config',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('n_questions', sa.Integer(), nullable=False),
    sa.Column('passing_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessment_config_id'), 'assessment_config', ['id'], unique=False)
    op.create_index(op.f('ix_assessment_config_kp_id'), 'assessment_config', ['kp_id'], unique=True)
    op.create_table('kp_exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kp_exercises_exercise_id'), 'kp_exercises', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_kp_exercises_id'), 'kp_exercises', ['id'], unique=False)
    op.create_index(op.f('ix_kp_exercises_kp_id'), 'kp_exercises', ['kp_id'], unique=False)
    op.create_table('kp_prerequisites',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('prerequisite_kp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kp_id', 'prerequisite_kp_id', name='uq_kp_prerequisite')
    )
    op.create_index(op.f('ix_kp_prerequisites_id'), 'kp_prerequisites', ['id'], unique=False)
    op.create_index(op.f('ix_kp_prerequisites_kp_id'), 'kp_prerequisites', ['kp_id'], unique=False)
    op.create_index(op.f('ix_kp_prerequisites_prerequisite_kp_id'), 'kp_prerequisites', ['prerequisite_kp_id'], unique=False)
    op.create_table('kp_questions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kp_questions_id'), 'kp_questions', ['id'], unique=False)
    op.create_index(op.f('ix_kp_questions_kp_id'), 'kp_questions', ['kp_id'], unique=False)
    op.create_index(op.f('ix_kp_questions_question_id'), 'kp_questions', ['question_id'], unique=False)
    op.create_table('kp_relations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('related_kp_id', sa.Uuid(), nullable=False),
    sa.Column('relation_type', sa.Enum('PREREQUISITE', 'COREQUISITE', 'RELATED_TO', 'PART_OF', 'EXAMPLE_OF', 'APPLICATION_OF', 'CONTRASTS_WITH', 'EXTENDS', 'SIMPLER_THAN', 'MORE_COMPLEX_THAN', 'ANALOGOUS_TO', 'DEPENDS_ON', name='relationtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kp_id', 'related_kp_id', 'relation_type', name='uq_kp_relation')
    )
    op.create_index(op.f('ix_kp_relations_id'), 'kp_relations', ['id'], unique=False)
    op.create_index(op.f('ix_kp_relations_kp_id'), 'kp_relations', ['kp_id'], unique=False)
    op.create_index(op.f('ix_kp_relations_related_kp_id'), 'kp_relations', ['related_kp_id'], unique=False)
    op.create_index(op.f('ix_kp_relations_relation_type'), 'kp_relations', ['relation_type'], unique=False)
    op.create_table('kp_resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kp_id', sa.Uuid(), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['kp_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kp_resources_id'), 'kp_resources', ['id'], unique=False)
    op.create_index(op.f('ix_kp_resources_kp_id'), 'kp_resources', ['kp_id'], unique=False)
    op.create_index(op.f('ix_kp_resources_resource_id'), 'kp_resources', ['resource_id'], unique=False)
    op.create_table('student_mastery',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_id', sa.Uuid(), nullable=False),
    sa.Column('knowledge_point_id', sa.Uuid(), nullable=False),
    sa.Column('section_id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.Uuid(), nullable=False),
    sa.Column('course_id', sa.Uuid(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('knowledge_score', sa.Float(), nullable=False),
    sa.Column('attitude_score', sa.Float(), nullable=False),
    sa.Column('combined_mastery', sa.Float(), nullable=False),
    sa.Column('mastery_group', sa.Enum('A', 'B', 'C', 'D', 'N', name='masterygroup'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('is_started', sa.Boolean(), nullable=False),
    sa.Column('last_assessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('total_time_spent', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['knowledge_point_id'], ['knowledge_points.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['sections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'knowledge_point_id', name='uq_student_kp_mastery')
    )
    op.create_index(op.f('ix_student_mastery_combined_mastery'), 'student_mastery', ['combined_mastery'], unique=False)
    op.create_index(op.f('ix_student_mastery_course_id'), 'student_mastery', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_mastery_id'), 'student_mastery', ['id'], unique=False)
    op.create_index(op.f('ix_student_mastery_is_available'), 'student_mastery', ['is_available'], unique=False)
    op.create_index(op.f('ix_student_mastery_is_started'), 'student_mastery', ['is_started'], unique=False)
    op.create_index(op.f('ix_student_mastery_knowledge_point_id'), 'student_mastery', ['knowledge_point_id'], unique=False)
    op.create_index(op.f('ix_student_mastery_mastery_group'), 'student_mastery', ['mastery_group'], unique=False)
    op.create_index(op.f('ix_student_mastery_module_id'), 'student_mastery', ['module_id'], unique=False)
    op.create_index(op.f('ix_student_mastery_section_id'), 'student_mastery', ['section_id'], unique=False)
    op.create_index(op.f('ix_student_mastery_student_id'), 'student_mastery', ['student_id'], unique=False)
    op.create_table('mastery_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('student_mastery_id', sa.Uuid(), nullable=False),
    sa.Column('skill_score', sa.Float(), nullable=False),
    sa.Column('knowledge_score', sa.Float(), nullable=False),
    sa.Column('attitude_score', sa.Float(), nullable=False),
    sa.Column('combined_mastery', sa.Float(), nullable=False),
    sa.Column('mastery_group', sa.Enum('A', 'B', 'C', 'D', 'N', name='masterygroup'), nullable=False),
    sa.Column('change_type', sa.Enum('QUIZ_COMPLETED', 'EXERCISE_SUBMITTED', 'VIDEO_WATCHED', 'CONTENT_READ', 'PEER_INTERACTION', 'MANUAL_ADJUSTMENT', 'SYSTEM_RECALCULATION', name='changetype'), nullable=False),
    sa.Column('previous_combined_mastery', sa.Float(), nullable=True),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('context_type', sa.String(length=50), nullable=True),
    sa.Column('context_id', sa.Uuid(), nullable=True),
    sa.Column('performance_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('time_spent_seconds', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('recorded_by', sa.String(length=50), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_mastery_id'], ['student_mastery.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mastery_history_change_type'), 'mastery_history', ['change_type'], unique=False)
    op.create_index(op.f('ix_mastery_history_id'), 'mastery_history', ['id'], unique=False)
    op.create_index(op.f('ix_mastery_history_recorded_at'), 'mastery_history', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_mastery_history_student_mastery_id'), 'mastery_history', ['student_mastery_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mastery_history_student_mastery_id'), table_name='mastery_history')
    op.drop_index(op.f('ix_mastery_history_recorded_at'), table_name='mastery_history')
    op.drop_index(op.f('ix_mastery_history_id'), table_name='mastery_history')
    op.drop_index(op.f('ix_mastery_history_change_type'), table_name='mastery_history')
    op.drop_table('mastery_history')
    op.drop_index(op.f('ix_student_mastery_student_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_section_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_module_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_mastery_group'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_knowledge_point_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_is_started'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_is_available'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_course_id'), table_name='student_mastery')
    op.drop_index(op.f('ix_student_mastery_combined_mastery'), table_name='student_mastery')
    op.drop_table('student_mastery')
    op.drop_index(op.f('ix_kp_resources_resource_id'), table_name='kp_resources')
    op.drop_index(op.f('ix_kp_resources_kp_id'), table_name='kp_resources')
    op.drop_index(op.f('ix_kp_resources_id'), table_name='kp_resources')
    op.drop_table('kp_resources')
    op.drop_index(op.f('ix_kp_relations_relation_type'), table_name='kp_relations')
    op.drop_index(op.f('ix_kp_relations_related_kp_id'), table_name='kp_relations')
    op.drop_index(op.f('ix_kp_relations_kp_id'), table_name='kp_relations')
    op.drop_index(op.f('ix_kp_relations_id'), table_name='kp_relations')
    op.drop_table('kp_relations')
    op.drop_index(op.f('ix_kp_questions_question_id'), table_name='kp_questions')
    op.drop_index(op.f('ix_kp_questions_kp_id'), table_name='kp_questions')
    op.drop_index(op.f('ix_kp_questions_id'), table_name='kp_questions')
    op.drop_table('kp_questions')
    op.drop_index(op.f('ix_kp_prerequisites_prerequisite_kp_id'), table_name='kp_prerequisites')
    op.drop_index(op.f('ix_kp_prerequisites_kp_id'), table_name='kp_prerequisites')
    op.drop_index(op.f('ix_kp_prerequisites_id'), table_name='kp_prerequisites')
    op.drop_table('kp_prerequisites')
    op.drop_index(op.f('ix_kp_exercises_kp_id'), table_name='kp_exercises')
    op.drop_index(op.f('ix_kp_exercises_id'), table_name='kp_exercises')
    op.drop_index(op.f('ix_kp_exercises_exercise_id'), table_name='kp_exercises')
    op.drop_table('kp_exercises')
    op.drop_index(op.f('ix_assessment_config_kp_id'), table_name='assessment_config')
    op.drop_index(op.f('ix_assessment_config_id'), table_name='assessment_config')
    op.drop_table('assessment_config')
    op.drop_index(op.f('ix_knowledge_points_section_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_module_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_kp_type'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_difficulty_level'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_course_id'), table_name='knowledge_points')
    op.drop_index(op.f('ix_knowledge_points_code'), table_name='knowledge_points')
    op.drop_table('knowledge_points')
    op.drop_index(op.f('ix_sections_module_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_id'), table_name='sections')
    op.drop_index(op.f('ix_sections_difficulty_level'), table_name='sections')
    op.drop_table('sections')
    op.drop_index(op.f('ix_modules_id'), table_name='modules')
    op.drop_index(op.f('ix_modules_difficulty_level'), table_name='modules')
    op.drop_index(op.f('ix_modules_course_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_enrollments_user_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_enrollment_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_profiles_user_id'), table_name='profiles')
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_courses_user_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_difficulty_level'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_resources_type'), table_name='resources')
    op.drop_index(op.f('ix_resources_id'), table_name='resources')
    op.drop_table('resources')
    op.drop_index(op.f('ix_questions_type'), table_name='questions')
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_difficulty_level'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty_level'), table_name='exercises')
    op.drop_table('exercises')
    # ### end Alembic commands ###
