"""fix

Revision ID: 47a5ad8f199d
Revises: add_performance_indexes
Create Date: 2025-11-23 14:31:14.798523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47a5ad8f199d'
down_revision: Union[str, None] = 'add_performance_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_student_mastery_course_lookup'), table_name='student_mastery')
    op.drop_index(op.f('idx_student_mastery_student_group'), table_name='student_mastery')
    op.drop_index(op.f('idx_student_mastery_student_lookup'), table_name='student_mastery')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_student_mastery_student_lookup'), 'student_mastery', ['student_id', 'combined_mastery', 'updated_at'], unique=False)
    op.create_index(op.f('idx_student_mastery_student_group'), 'student_mastery', ['student_id', 'mastery_group'], unique=False)
    op.create_index(op.f('idx_student_mastery_course_lookup'), 'student_mastery', ['student_id', 'course_id', 'combined_mastery'], unique=False)
    # ### end Alembic commands ###
